apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mall-admin-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mall-admin
    spec:
      containers:
      - name: mall-admin
        image: bbbenpjr/{image}
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mall-admin-svc
spec:
  type: NodePort
  selector:
    run: mall-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080